Add Key Vault article
Azure-Samples/migrate-javaee-app-to-azure-training pull request #7
Opened 2021-04-27 20:42 UTC by JasonFreeberg

2021-05-11 02:59 UTC, selvasingh requested changes

2021-05-11 02:59 UTC, selvasingh commented on step-06-secure-secrets-in-key-vault/README.md
> +    az keyvault create --name jboss-app-key-vault              \
For name, resource group and location, we should rely on environment variables. Those variables should be derived from how we have requested users to create a copy of https://github.com/Azure-Samples/migrate-javaee-app-to-azure-training/blob/main/setup-env-variables-template.sh

2021-05-11 02:59 UTC, selvasingh commented on step-06-secure-secrets-in-key-vault/README.md
> +    az keyvault set-policy --name java-app-key-vault     \
We should add an additional environment variable and set the object id before calling this cli command

2021-05-11 02:59 UTC, selvasingh commented on step-06-secure-secrets-in-key-vault/README.md
> +    az keyvault secret set --name POSTGRES_SERVER_ADMIN_FULL_NAME \
Vault name should be retrieved from an environment variable

2021-05-11 02:59 UTC, selvasingh commented on step-06-secure-secrets-in-key-vault/README.md
> +    az keyvault secret show --vault-name java-app-key-vault --name POSTGRES-URL
Vault name should be retrieved from an environment variable

2021-05-11 02:59 UTC, selvasingh commented on step-06-secure-secrets-in-key-vault/README.md
> +    az webapp config appsettings set -n <your_app_name> -g <resource_group> --settings \
Spring? :-)

2021-05-11 02:59 UTC, selvasingh commented on step-06-secure-secrets-in-key-vault/README.md
> +    az keyvault secret set --name POSTGRES_SERVER_ADMIN_FULL_NAME \
We should have 3 sub sections for each of the databases - SQL, PostgreSQL and MySQL

2021-06-18 18:50 UTC, JasonFreeberg commented on step-06-secure-secrets-in-key-vault/README.md
> +    az webapp config appsettings set -n <your_app_name> -g <resource_group> --settings \
Copied from my older article

2021-11-04 00:44 UTC, closed without merging